---
title: "Differential abundance analysis"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---


```{r setup, echo=F, message=F, error=F}
knitr::opts_chunk$set(echo = T, message = F, warning = F, fig.align = "center")
```


```{r}
# load libraries
library(tidyverse)
library(patchwork)
library(Seurat)
library(DESeq2)

# load the plot theme
source("/g/huber/users/hirschmueller/DECODE/MasterThesis/scripts/plot_theme.R")
```

```{r}
seurat <- qs::qread("/g/huber/users/hirschmueller/DECODE/analysis/notch_3prime/results/integration_notch_ctrl/ctrl_notch_reference_integration.qs")

# rename celltypes and remove celltypes we are not interested in.
seurat@meta.data$tmp_celltype <- case_when(
  seurat$celltype_manual %in% c("daEC","dEC", "MT") ~ NA_character_,
  grepl("EC",seurat$celltype_manual) ~ "EC",
  seurat$celltype_manual == "R3" ~ "EC",
  seurat$celltype_manual == "Copper" ~ "EC",
  grepl("EB",seurat$celltype_manual) ~ "EB",
  grepl("unk",seurat$celltype_manual) ~ NA_character_, # exclude from analysis
  T ~ seurat$celltype_manual
  )

seurat@meta.data$orig.ident <- case_when(
  seurat$orig.ident == "TX22" ~ "Control Replicate 1",
  seurat$orig.ident == "TX23"~ "Control Replicate 2",
  seurat$orig.ident == "TX22_N"~ "Notch Replicate 1",
  seurat$orig.ident == "TX23_N"~ "Notch Replicate 2",
) %>% factor(., levels = c("Control Replicate 1", "Control Replicate 2",
                           "Notch Replicate 1","Notch Replicate 2"))

seurat_subset <- seurat[,!is.na(seurat$tmp_celltype)]
```

```{r}
# creat "count table" for DESeq2
cnts <- seurat_subset@meta.data %>% 
  group_by(orig.ident, tmp_celltype) %>% 
  tally() %>% 
  pivot_wider(., names_from = "orig.ident",
              values_from = "n") %>% 
  column_to_rownames("tmp_celltype") %>% 
  na.omit(.) %>%  # remove all rows with NA 
  as.matrix()

# define model matrix
exp_design <- seurat_subset@meta.data[,c("orig.ident", "perturbation")] %>%
  data.frame() %>%
  distinct()
exp_design$orig.ident <- factor(exp_design$orig.ident, levels=c("Control Replicate 1", "Control Replicate 2",
                           "Notch Replicate 1","Notch Replicate 2"))
rownames(exp_design) <- exp_design$orig.ident
model <- model.matrix(~ perturbation, data = exp_design)


dds <- DESeqDataSetFromMatrix(countData = cnts,
                              colData = exp_design,
                              design = ~perturbation)

# we dont use deseq2 to calculate norm factors because it assumes that majority of genes (in this case celltypes) dont change. This assumption doesnt hold in our case.
sizeFactors(dds) = colSums(cnts)/mean(colSums(cnts))

result <- DESeq(dds)


out_deseq <- results(result) %>% 
  data.frame() %>% 
  arrange(padj)
```

```{r}
# visualize results
coarse_annotation_plot <- counts(dds, norm=T) %>% 
  data.frame() %>% 
  rownames_to_column("celltype") %>% 
  pivot_longer(-celltype,names_to = "replicate", values_to = "n_cells") %>% 
  mutate(celltype=factor(celltype, levels=c("ISC","EE","EB","EC"))) %>% 
  mutate(replicate = str_replace_all(.$replicate,"\\."," ")) %>% 
 mutate(replicate=factor(replicate,levels=c("Control Replicate 1","Control Replicate 2","Notch Replicate 1","Notch Replicate 2"))) %>%
  mutate(Condition = ifelse(grepl("Notch",replicate), "Notch-knockout","Control")) %>% 
  ggplot(., aes(x=Condition, y=n_cells,color=replicate))+
  geom_point()+
  stat_summary(fun="mean", geom="crossbar",
                 mapping=aes(ymin=..y.., ymax=..y..), width=0.22,
                 position=position_dodge(),show.legend = FALSE, color="red")+
  facet_wrap(~celltype, scales = "free_y") + 
  ylab("Normalized number of cells") +
  theme_Publication() +
  theme(legend.title = element_blank())+
  scale_color_manual(values=color_mapping)+
  guides(color=guide_legend(nrow=2,byrow=F))+
  ggtitle("Midgut cell\npopulations")
```


## Do the same analysis, but this time for the EE subtypes. 
```{r}
# load EE classification:
notch_ee <- data.table::fread("/g/huber/users/hirschmueller/DECODE/analysis/notch_3prime/results/subclustering/EE/mdata_ee_classification.tsv",
                             data.table = F)

ctrl_ee <- data.table::fread("/g/huber/users/hirschmueller/DECODE/analysis/ctrl_3prime/results/subclustering/EE/mdata_ee_classification.tsv",
                              data.table = F)


ees <- rbind(notch_ee,ctrl_ee) %>% 
  mutate(orig.ident = sapply(str_match_all(Barcode_unique,"TX\\d\\d(_N)?"),function(x) x[,1])) %>% 
  mutate(orig.ident = case_when(
    .$orig.ident == "TX22" ~ "Control Replicate 1",
    .$orig.ident == "TX23"~ "Control Replicate 2",
    .$orig.ident == "TX22_N"~ "Notch Replicate 1",
    .$orig.ident == "TX23_N"~ "Notch Replicate 2",
  )) %>% 
  mutate(orig.ident = factor(orig.ident, 
                             levels = c("Control Replicate 1", "Control Replicate 2",
                                        "Notch Replicate 1","Notch Replicate 2")))


cnts <- ees %>% 
  group_by(orig.ident, EE_subtype) %>% 
  tally() %>% 
  pivot_wider(., names_from = "orig.ident",
              values_from = "n") %>% 
  filter(!EE_subtype %in% c("unk-EE", "aEC-EE")) %>% # only analyze cells of certain origin
  column_to_rownames("EE_subtype") %>% 
  na.omit(.) %>%  # remove all rows with NA 
  as.matrix() 

dds <- DESeqDataSetFromMatrix(countData = cnts,
                              colData = exp_design,
                              design = ~perturbation)
sizeFactors(dds) = colSums(cnts)/mean(colSums(cnts))

result <- DESeq(dds)
deseq_res_ee <- results(result) %>% 
  data.frame() %>% 
  arrange(padj)

```

```{r}
# visualize ee change
ee_annotation_plot<-counts(dds, norm=T) %>% 
  data.frame() %>% 
  rownames_to_column("celltype") %>% 
  pivot_longer(-celltype,names_to = "replicate", values_to = "n_cells") %>% 
  mutate(celltype=factor(celltype, levels=c("AstC-EE","EEP","Tk-EE","classIII-EE", "unk-EE","aEC-EE"))) %>% 
  mutate(replicate = str_replace_all(.$replicate,"\\."," ")) %>% 
 mutate(replicate=factor(replicate,levels=c("Control Replicate 1","Control Replicate 2","Notch Replicate 1","Notch Replicate 2"))) %>%
  mutate(Condition = ifelse(grepl("Notch",replicate), "Notch-knockout","Control")) %>% 
  ggplot(., aes(x=Condition, y=n_cells,color=replicate))+
  geom_point()+
  stat_summary(fun="mean", geom="crossbar",
                 mapping=aes(ymin=..y.., ymax=..y..), width=0.22,
                 position=position_dodge(),show.legend = FALSE, color="red")+
  facet_wrap(~celltype, scales = "free_y") + 
  ylab("Normalized number of cells") +
  theme_Publication() +
  theme(legend.title = element_blank())+
  scale_color_manual(values=color_mapping)+
  guides(color=guide_legend(nrow=2,byrow=F))+
  ggtitle("Enteroendocrine cell\npopulations")


```

## combine plot
```{r}
combined_plot <- wrap_plots(coarse_annotation_plot, plot_spacer(), ee_annotation_plot,
           nrow=1)+
  plot_layout(widths = c(1,0.1,1), guides = "collect")+
  plot_annotation(tag_levels = "A") & 
  theme(plot.tag = element_text(size = 18, face="bold"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.text = element_text(size=9),
        plot.title = element_text(size=12.5, face="bold",hjust=0.5))

ragg::agg_png("/g/huber/users/hirschmueller/DECODE/MasterThesis/plots/differential_abundance.png", width = 14, height = 6.6, res=800, units = "cm", scaling = 0.5)
combined_plot
dev.off()

```

```{r, eval=F}
rmarkdown::render("/g/huber/users/hirschmueller/DECODE/MasterThesis/scripts/differential_abundance.Rmd",
                  output_dir = "/g/huber/users/hirschmueller/DECODE/MasterThesis/html/")
```


```{r}
sessionInfo()
```