---
title: "Novel marker genes"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---


```{r setup, echo=F, message=F, error=F}
knitr::opts_chunk$set(echo = T, message = F, warning = F, fig.align = "center")
```


```{r}
# load libraries
library(tidyverse)
library(patchwork)
library(Seurat)

# load the plot theme
source("/g/huber/users/hirschmueller/DECODE/MasterThesis/scripts/plot_theme.R")
```


### Load data
```{r}
# load the data
ctrl <- qs::qread("/g/huber/users/hirschmueller/DECODE/analysis/ctrl_3prime/results/integration/seurat_integration.qs")
ctrl$celltype_manual <- ifelse(ctrl$celltype_manual == "HSP-EB", "EB", ctrl$celltype_manual)
ctrl$celltype_manual <- ifelse(ctrl$celltype_manual == "R3", "mEC", ctrl$celltype_manual)
```


```{r}
# define a color palette for our data
color_palette <- c("#009E73", "#56B4E9", "#E69F00", "#C7B900", "#D55E00", "#CC79A7", "#8EBD59", "#663399","#999999", "#EB6864", "#709DAD")



# we have to turn the celltype into a factor with the same ordering for both ctrl and notch.
ctrl$celltype_manual <- factor(ctrl$celltype_manual, 
                                          levels = c("ISC", "EB", "daEC" ,"aEC", "Copper","pEC", "EE", "unk","MT", "dEC","mEC"))

genes <- c("OtopLb", "Pgcl",
           "CG5107","CG17192",
           "kibra", "hdly")

##############
# CTRL PLOTS #
##############
annotation_plot_ctrl <- DimPlot(ctrl,
        group.by = "celltype_manual",
        label=T,
        repel = T,
        label.size = 3.9,
        pt.size = 0.01,
        raster = F,
        label.box = T)+
  theme_UMAP() +
  theme(legend.position = "none",
        strip.text = element_text(face = "bold"))+
  scale_color_manual(values = color_palette[1:n_distinct(ctrl$celltype_manual)])+
  scale_fill_manual(values = color_palette[1:n_distinct(ctrl$celltype_manual)])+
  scale_y_reverse() + # purely for visualization, so they are aligned like the notch.
  ggtitle("Control\nCondition")

gene_plot_ctrl <- FeaturePlot(ctrl, genes,ncol = 2, pt.size = 0.01, order = F) &
  scale_y_reverse() &
  scale_color_gradient(low="lightgrey",high = "darkred") &
  theme_UMAP() &
  theme(legend.direction = "vertical",
        legend.position = "right",
        legend.text = element_text(size=10),
        plot.title = element_text(size=12.5, hjust = 0.5, face="bold"),
        plot.margin = unit(c(1,1,7,1),"mm"))


layout=' 
##BBBB
##BBBB
AABBBB
AABBBB
AABBBB
AABBBB
##BBBB
##BBBB
' 

ctrl_plot <-wrap_plots(annotation_plot_ctrl, gene_plot_ctrl) + 
  plot_layout(design=layout)
```


```{r}
ragg::agg_png("/g/huber/users/hirschmueller/DECODE/MasterThesis/plots/novel_marker_expression.png", width = 16, height = 12,
              res=600, units = "cm", scaling = 0.5)
ctrl_plot
dev.off()



```


```{r, eval=F, echo=F}
rmarkdown::render("/g/huber/users/hirschmueller/DECODE/MasterThesis/scripts/trypsin_expression.Rmd",
                  output_dir = "/g/huber/users/hirschmueller/DECODE/MasterThesis/html/")
```


```{r}
sessionInfo()
```










