---
title: "DECODE Preprocessing & Filtering"
author: "Nick Hirschmüller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---


```{r setup, echo=F, message=F, error=F}
knitr::opts_chunk$set(echo = T, message = F, warning = F, fig.align = "center")
```


### Introduction
Shows the general overview of the data. Complex Heatmaps are a bit odd to combine in patchworks. Thus we generate the elements here and combine them manually later...


```{r}
# load libraries
library(tidyverse)
library(scran)
library(scales)
library(patchwork)
library(parallel)
library(Seurat)
library(ComplexHeatmap)
library(circlize)

# load the plot theme
source("/g/huber/users/hirschmueller/DECODE/MasterThesis/scripts/plot_theme.R")
```

```{r}
# easy function to plot heatmap for set of genes. each column is one cell
marker_heatmap <- function(seurat, markers, celltype, group.by, cap_value=NULL){
  # plot a heatmap, where each column is one cell! The cells are grouped and split according to the cluster they are from 
  
  ordered_index <- order(seurat@meta.data[[group.by]])
  c_split <- sort(seurat@meta.data[[group.by]])
  
  if (!all(markers %in% rownames(seurat@assays$RNA))){
    mising_genes <- paste(markers[!markers %in% rownames(seurat@assays$RNA)], sep=", ")
    celltype <- celltype[markers %in% rownames(seurat@assays$RNA)]
    markers <- markers[markers %in% rownames(seurat@assays$RNA)]
    print(str_interp("Not all markers occur in the data matrix of the seurat object. Specifically, ${mising_genes} are missing. Removing it and continuing"))
  }
  
  # get counts and perform gene wise scaling
  cnts_scaled <- as.matrix(seurat@assays$RNA[markers, ordered_index]) %>% 
    t() %>% 
    scale() %>% 
    t()
  
  
  
  if(!is.null(cap_value)){
    message(str_interp("Zscores > |${cap_value}| are set to ${cap_value} (or -${cap_value})"))
    changed_values <- sum(cnts_scaled>cap_value) + sum(cnts_scaled < -cap_value)
    cnts_scaled[cnts_scaled>cap_value] = cap_value 
    cnts_scaled[cnts_scaled < -cap_value] = -cap_value 
    message(str_interp("This was the case for ${changed_values} values"))
    col_fun = colorRamp2(c(-cap_value, 0, cap_value), c("blue", "white", "red"))
    
  } else {col_fun = colorRamp2(breaks=c(min(cnts_scaled, na.rm=T), mean(cnts_scaled, na.rm=T), max(cnts_scaled, na.rm=T)),
                     colors=c("blue", "white", "red"))}

  p <- Heatmap(cnts_scaled,
               cluster_rows = F, 
               cluster_columns = F, 
               show_row_names = T, 
               show_column_names = F,
               column_split = c_split,
               row_split = celltype,
               show_heatmap_legend = F,
               name="Z-score",
               col=col_fun,
               row_gap = unit(1, "mm"),
               column_gap = unit(1, "mm"),
               border_gp = grid::gpar(col = "black", lwd = 0.5),
               column_title_gp = grid::gpar(fontsize = 7),
               column_title_rot = 90,
               row_names_gp = grid::gpar(fontsize = 7),
               row_title_gp = grid::gpar(fontsize = 7),
               row_title_rot = 0,
               use_raster = F,
               heatmap_legend_param = list(at = c(-cap_value, 0, cap_value)))
  return(p)
}

```


```{r}
# load the data
notch_integrated <- qs::qread("/g/huber/users/hirschmueller/DECODE/analysis/notch_3prime/results/integration/seurat_integration.qs")

notch_integrated$celltype_manual <- ifelse(notch_integrated$celltype_manual == "unk2", "unk", notch_integrated$celltype_manual)

# also some MT cells are labeled as pEC. This is because for the resolution that we chose, they were aggregated as one cluster and in that cluster pEC markers dominate. 
# however the cells belonging to MT express specificall Smvt and ct (and are also predicted to be MT using the flygut atlas).
MT_cells <-c("TX22_N_ACGTCCTAGTAAACAC-1", "TX22_N_ACTTATCGTAAGCTCT-1", "TX22_N_AGGCCACAGCTGAGTG-1",
         "TX22_N_AGTGTTGCACAATGAA-1", "TX22_N_ATCACTTTCAGTGTTG-1", "TX22_N_ATCGTCCAGGGATCGT-1",
         "TX22_N_ATTCAGGCACTGGATT-1", "TX22_N_CAGCGTGCAACGTATC-1", "TX22_N_CAGTGCGCAAACGAGC-1",
         "TX22_N_CAGTTCCTCCGTAATG-1", "TX22_N_CATCCCATCATGCAGT-1", "TX22_N_CATGCCTAGCGTTCCG-1",
         "TX22_N_CCGGTAGTCAAGGACG-1", "TX22_N_CTCAAGAAGAAACTCA-1", "TX22_N_GCCATTCGTACCGGAA-1",
         "TX22_N_GCCCGAACATAAGATG-1", "TX22_N_GGTCACGCAGCGATTT-1", "TX22_N_GGTGAAGGTACTGCCG-1",
         "TX22_N_GTACAGTGTAGGTAGC-1", "TX22_N_TAAGCCAGTGTCCATA-1", "TX22_N_TACCCGTGTTGGGACA-1",
         "TX22_N_TCCACGTAGTGCAACG-1", "TX22_N_TGGATCATCGGTAGAG-1", "TX22_N_TGTCCACAGGTACCTT-1",
         "TX22_N_TGTCCCAAGCCATTGT-1", "TX22_N_TTGTGTTGTAGCACGA-1", "TX22_N_TTTCCTCAGGACAACC-1",
         "TX23_N_AACCTTTGTGTTTGCA-1", "TX23_N_ACACGCGCAAGTGTCT-1", "TX23_N_ATCGATGGTTCGCGTG-1",
         "TX23_N_CATGAGTGTGCAATAA-1", "TX23_N_CGTTGGGCAGACGCTC-1", "TX23_N_CTCCATGCACACCTGG-1",
         "TX23_N_GCTTGGGAGAATTTGG-1", "TX23_N_GGAGGTAAGACATCAA-1", "TX23_N_GTCTAGAGTTGCCATA-1",
         "TX23_N_TACAGGTAGACCACGA-1", "TX23_N_TATCCTAGTATGCTAC-1", "TX23_N_TCACTATAGTCCCAAT-1",
         "TX23_N_TTGAACGGTGCACATT-1", "TX23_N_TTGGATGAGCATCCCG-1")
  
notch_integrated$celltype_manual <- ifelse(rownames(notch_integrated@meta.data) %in% MT_cells,
                                           "MT",
                                           notch_integrated$celltype_manual)



ctrl_integrated <- qs::qread("/g/huber/users/hirschmueller/DECODE/analysis/ctrl_3prime/results/integration/seurat_integration.qs")
ctrl_integrated$celltype_manual <- ifelse(ctrl_integrated$celltype_manual == "HSP-EB", "EB", ctrl_integrated$celltype_manual)
ctrl_integrated$celltype_manual <- ifelse(ctrl_integrated$celltype_manual == "R3", "mEC", ctrl_integrated$celltype_manual)
```

### UMAPs
```{r, fig.height=17, fig.width=9, dpi=300}
# define a color palette for our data
color_palette <- c("#009E73", "#56B4E9", "#E69F00", "#C7B900", "#D55E00", "#CC79A7", "#8EBD59", "#663399","#999999", "#EB6864", "#709DAD")



# we have to turn the celltype into a factor with the same ordering for both ctrl and notch.
ctrl_integrated$celltype_manual <- factor(ctrl_integrated$celltype_manual, 
                                          levels = c("ISC", "EB", "daEC" ,"aEC", "Copper","pEC", "EE", "unk","MT", "dEC","mEC"))

notch_integrated$celltype_manual <- factor(notch_integrated$celltype_manual, 
                                          levels = c("ISC", "EB", "daEC" ,"aEC", "Copper","pEC", "EE", "unk", "MT"))

#############
# PLOT CTRL #
#############
ctrl_umap <- DimPlot(ctrl_integrated,
        group.by = "celltype_manual",
        label=T,
        repel = T,
        label.size = 4.6,
        pt.size = 0.01,
        raster = F,
        label.box = T)+
  theme_UMAP() +
  theme(legend.position = "none",
        strip.text = element_text(face = "bold"),
        plot.title = element_blank())+
  scale_color_manual(values = color_palette[1:n_distinct(ctrl_integrated$celltype_manual)])+
  scale_fill_manual(values = color_palette[1:n_distinct(ctrl_integrated$celltype_manual)])+
  scale_y_reverse() # purely for visualization, so they are aligned like the notch.


ragg::agg_png("/g/huber/users/hirschmueller/DECODE/MasterThesis/plots/ctrl_umap.png", width = 8.71, height = 8.08,
              res=800, units = "cm", scaling = 0.7)
ctrl_umap
dev.off()




##############
# PLOT NOTCH #
##############
notch_umap <- DimPlot(notch_integrated,
        group.by = "celltype_manual",
        label=T,
        repel = T,
        label.size = 4.6,
        pt.size = 0.01,
        raster = F,
        label.box = T)+
  theme_UMAP() +
  theme(legend.position = "none",
        strip.text = element_text(face = "bold"),
        plot.title = element_blank())+
  scale_color_manual(values = color_palette[1:n_distinct(notch_integrated$celltype_manual)])+
  scale_fill_manual(values = color_palette[1:n_distinct(notch_integrated$celltype_manual)])+
  scale_x_reverse() # purely for visualization, so they are aligned like the ctrl.
notch_umap

ragg::agg_png("/g/huber/users/hirschmueller/DECODE/MasterThesis/plots/notch_umap.png", width = 8.71, height = 8.08,
              res=800, units = "cm", scaling = 0.7)
notch_umap
dev.off()


###############
# PLOT LEGEND #
###############
ctrl_integrated$legend_title <- case_when(
  ctrl_integrated$celltype_manual == "ISC" ~ "ISC ≙ intestinal stem cells",
  ctrl_integrated$celltype_manual == "aEC" ~ "aEC ≙ anterior enterocytes",
  ctrl_integrated$celltype_manual == "daEC" ~ "daEC ≙ adifferentiating anterior enterocytes",
  ctrl_integrated$celltype_manual == "pEC" ~ "pEC ≙ posterior enterocytes",
  ctrl_integrated$celltype_manual == "Copper" ~ "Copper ≙ Copper cells",
  ctrl_integrated$celltype_manual == "dEC" ~ "dEC ≙ differentiating enterocytes",
  ctrl_integrated$celltype_manual == "EB" ~ "EB ≙ Enteroblasts",
  ctrl_integrated$celltype_manual == "EE" ~ "EE ≙ Enteroendocrine cells",
  ctrl_integrated$celltype_manual == "MT" ~ "MT ≙ Malpighian tubule cells",
  ctrl_integrated$celltype_manual == "unk" ~ "unk ≙ unkown",
  ctrl_integrated$celltype_manual == "mEC" ~ "mEC ≙ middle enterocytes",
)


ctrl_integrated$legend_title <- factor(ctrl_integrated$legend_title, 
                                          levels = c("ISC ≙ intestinal stem cells", 
                                                     "EB ≙ Enteroblasts", 
                                                     "daEC ≙ adifferentiating anterior enterocytes",
                                                     "aEC ≙ anterior enterocytes", 
                                                     "Copper ≙ Copper cells",
                                                     "pEC ≙ posterior enterocytes",
                                                     "EE ≙ Enteroendocrine cells",
                                                     "unk ≙ unkown",
                                                     "MT ≙ Malpighian tubule cells",
                                                     "dEC ≙ differentiating enterocytes",
                                                     "mEC ≙ middle enterocytes"))

lgd_dimplot <- DimPlot(ctrl_integrated,
        group.by = "legend_title")+
  scale_color_manual(values = color_palette[1:n_distinct(ctrl_integrated$celltype_manual)]) +
  guides(color = guide_legend(byrow = TRUE, override.aes = list(size=2.5))) +
  theme(legend.spacing.y = unit(2, "mm"))
lgd_dimplot <- cowplot::get_legend(lgd_dimplot) %>% ggplotify::as.ggplot()

ragg::agg_png("/g/huber/users/hirschmueller/DECODE/MasterThesis/plots/legend_umap.png", width = 8.71, height =9.401528,
              res=1000, units = "cm", scaling = 0.7)
lgd_dimplot
dev.off()





```


### Heatmaps
```{r}
# for the heatmaps we remove unk and MT population, simply because there are only ~50 cells each. If we would include them in the heatmap, we wouldnt see anything anyway
ctrl_heatmap <- ctrl_integrated[,ctrl_integrated$celltype_manual %in% c("ISC", "EB", "daEC" ,"aEC", "Copper","pEC", "EE", "dEC","mEC")]
notch_heatmap <- notch_integrated[,notch_integrated$celltype_manual %in% c("ISC", "EB", "daEC" ,"aEC", "Copper","pEC", "EE")]

#############
# PLOT CTRL #
#############
ctrl_heatmap$celltype_manual <- factor(ctrl_heatmap$celltype_manual, 
                                          levels = c("ISC", "EB", "daEC" ,"aEC", "Copper","pEC", "EE", "dEC","mEC"))


# based on literature and flygut atlas
marker_table <- data.frame(gene=c("alphaTry", "epsilonTry",
                                  "nub", 
                                  "esg", "kay", "E(spl)mbeta-HLH",
                                  "Dl",
                                  "Vha100-4", "Vha16-1",
                                  "pros", "7B2", 
                                  "lambdaTry","LManVI", 
                                  "thetaTry", "Npc2f"),
                           
                           celltype=c("aEC", "aEC", 
                                      "dEC",  
                                      "EB", "EB", "EB", 
                                      "ISC",
                                      "Copper", "Copper",
                                      "EE", "EE",
                                      "pEC", "pEC",
                                      "mEC", "mEC"))

marker_table$celltype <- factor(marker_table$celltype, levels=levels(ctrl_heatmap$celltype_manual))
ht_opt(TITLE_PADDING=unit(1,"mm"))

# draw heatmap
heatmap_ctrl<-marker_heatmap(seurat = ctrl_heatmap,
               markers = marker_table$gene,
               celltype = marker_table$celltype,
               group.by = "celltype_manual",
               cap_value = 2)

ragg::agg_png("/g/huber/users/hirschmueller/DECODE/MasterThesis/plots/heatmap_ctrl.png", width = 6.2, height = 4.3,
              res=800, units = "cm", scaling = 0.5)
draw(heatmap_ctrl, padding = unit(c(2, 2,4, 2), "mm"), 
     row_title = "Celltype marker", row_title_gp = grid::gpar(fontsize = 10),
     column_title = "Assigned celltype label\n\n", column_title_gp = grid::gpar(fontsize = 10))

dev.off()

# draw legend
lgd <- Legend(at = c(-2, -1, 0, 1, 2), col_fun=colorRamp2(c(-2, 0, 2), c("blue", "white", "red")), title="Z-score",
               direction = "horizontal", legend_width = unit(30,"mm"), title_position = "topcenter")

ragg::agg_png(filename = "/g/huber/users/hirschmueller/DECODE/MasterThesis/plots/heatmap_celltype_legend_agg.png",
              width=10.66, height = 8.38, units="cm",res=800)
draw(lgd)
dev.off()



##############
# PLOT NOTCH #
##############
notch_heatmap$celltype_manual <- factor(notch_heatmap$celltype_manual, 
                                          levels = c("ISC", "EB", "daEC" ,"aEC", "Copper","pEC", "EE"))
# based on literature and flygut atlas
marker_table <- data.frame(gene=c("alphaTry", "epsilonTry",
                                  "esg", "kay", "E(spl)mbeta-HLH",
                                  "Dl",
                                  "Vha100-4", "Vha16-1",
                                  "pros", "7B2", 
                                  "lambdaTry","LManVI"),
                           
                           celltype=c("aEC", "aEC", 
                                      "EB", "EB", "EB", 
                                      "ISC",
                                      "Copper", "Copper",
                                      "EE", "EE",
                                      "pEC", "pEC"))
marker_table$celltype <- factor(marker_table$celltype, levels=levels(notch_heatmap$celltype_manual))

# draw heatmap
heatmap_notch<-marker_heatmap(seurat = notch_heatmap,
               markers = marker_table$gene,
               celltype = marker_table$celltype,
               group.by = "celltype_manual",
               cap_value = 2)

ragg::agg_png("/g/huber/users/hirschmueller/DECODE/MasterThesis/plots/heatmap_notch.png", width = 6.2, height = 4.3,
              res=800, units = "cm", scaling = 0.5)
draw(heatmap_notch, padding = unit(c(10, 2,4, 2), "mm"), 
     row_title = "Celltype marker", row_title_gp = grid::gpar(fontsize = 10),
     column_title = "Assigned celltype label\n\n", column_title_gp = grid::gpar(fontsize = 10))
dev.off()











```



```{r}
rmarkdown::render("/g/huber/users/hirschmueller/DECODE/MasterThesis/scripts/overview_fig1.Rmd", 
                  output_dir = "/g/huber/users/hirschmueller/DECODE/MasterThesis/html")
```



```{r}
sessionInfo()
```

















